### ISSUE TITLE
logging doesn't match actual calculation

### ISSUE THREAD

**Issue by MikePlante1** [Artificial-Pancreas/oref2#4]
`overrideFactor` is not included in this `maxBolus` calculation, but is included in the console logging for this calculation, so either the comment or the calculation should be changed at Line 1927-1928 in `determine-basal.js` :

```js
console.error(".maxSMBBasalMinutes: " + smbMinutesSetting + ", profile.current_basal: " + profile.current_basal * overrideFactor);
maxBolus = round(profile.current_basal * smbMinutesSetting / 60 ,1);
```

For comparison, `overrideFactor` **_is_** being used in the other three `maxBolus` calculations on lines 1908, 1918, and 1921

```js
maxBolus = round(profile.current_basal *overrideFactor * 30 / 60 ,1);
maxBolus = round(profile.current_basal * overrideFactor * uamMinutesSetting / 60 ,1);
maxBolus = round( profile.current_basal  * overrideFactor * 30 / 60 ,1);
```

**Comment by Jon-b-m** [comment]
OK, thanks. Pushed iAPS.
